import { app, BrowserWindow } from 'electron';
import { startServer } from '../../index.js'
import { start } from 'repl';
import { DATA_PORT } from '../../index.js';
import squirrelStartup from 'electron-squirrel-startup';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.

if (squirrelStartup) {
  app.quit();
}

const createWindow = (
  port: number
): BrowserWindow => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
  });

  mainWindow.setMenu(null);
  mainWindow.loadURL(`http://localhost:${port}`);

  // Open the DevTools.
  // mainWindow.webContents.openDevTools();

  return mainWindow
};


export const initApp = async () => {
  try {
    // Сначала запускаем ваш сервер (если он асинхронный — через await)
    console.log('Starting Express server...');
    await startServer(DATA_PORT); 

    // Ждем готовности Electron
    await app.whenReady();
    
    createWindow(DATA_PORT);

    // Стандартные события жизненного цикла
    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) createWindow(DATA_PORT);
    });
  } catch (err) {
    console.error('Failed to start app:', err);
    app.quit();
  }
};

initApp();

// Обработка закрытия (вне функции)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});