import { app, BrowserWindow, globalShortcut } from 'electron';
import startServer from '../../index.js'
import DATA_PORT from '../../port.js'
import squirrelStartup from 'electron-squirrel-startup';
// import { fileURLToPath } from 'url';
// import path from 'path'

// const __filename = fileURLToPath(import.meta.url);
// const __dirname = path.dirname(__filename);


// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

type TCreateWindow = (port: number) => BrowserWindow
type TInit = () => void

// Handle creating/removing shortcuts on Windows when installing/uninstalling.

if (squirrelStartup) {
  app.quit();
}

const createWindow: TCreateWindow = (
  port: number
) => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 720,
    width: 1280,
  });

  mainWindow.setMenu(null);
  mainWindow.loadURL(`http://localhost:${port}`);

  globalShortcut.register('CommandOrControl+R', () => {
        // Выполняем только если окно в фокусе, чтобы не мешать другим программам
        if (mainWindow.isFocused()) {
            mainWindow.reload();
        }
    });
  // Open the DevTools.
  // mainWindow.webContents.openDevTools();

  return mainWindow
};

export const initApp: TInit = async () => {
  try {
    // Сначала запускаем ваш сервер (если он асинхронный — через await)
    console.log('Starting Express server...');
    await startServer(DATA_PORT); 

    // Ждем готовности Electron
    await app.whenReady();
    
    createWindow(DATA_PORT);

    // Стандартные события жизненного цикла
    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) createWindow(DATA_PORT);
    });
  } catch (err) {
    console.error('Failed to start app:', err);
    app.quit();
  }
};

initApp();

// Обработка закрытия (вне функции)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});